"""empty message

Revision ID: 611cc14a5ca9
Revises: d4a7d54aea69
Create Date: 2025-04-09 01:11:26.497260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '611cc14a5ca9'
down_revision = 'd4a7d54aea69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_pkey')
    )
    # ### end Alembic commands ###
