"""Add reset_token columns to User

Revision ID: 80882fad249f
Revises: 611cc14a5ca9
Create Date: 2025-04-13 00:31:03.915074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80882fad249f'
down_revision = '611cc14a5ca9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('reset_token_expires', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('reset_token_expires')
        batch_op.drop_column('reset_token')

    # ### end Alembic commands ###
